spring:
  application:
    name: creator-agent

server:
  address: ${SERVER_ADDRESS:127.0.0.1}
  port: ${SERVER_PORT:18080}

management:
  endpoints:
    web:
      base-path: /api
      exposure:
        include: health
  endpoint:
    health:
      show-details: never
